# for cmd in choose confirm file filter format input join pager spin style table write log; do gum $cmd --help; done

# choose
export GUM_CHOOSE_CURSOR_FOREGROUND=3
export GUM_CHOOSE_HEADER_FOREGROUND=6
export GUM_CHOOSE_ITEM_FOREGROUND=7
export GUM_CHOOSE_SELECTED_FOREGROUND=4

# confirm
export GUM_CONFIRM_PROMPT_FOREGROUND=6
export GUM_CONFIRM_SELECTED_FOREGROUND=7
export GUM_CONFIRM_UNSELECTED_FOREGROUND=7
export GUM_CONFIRM_SELECTED_BACKGROUND=4
export GUM_CONFIRM_UNSELECTED_BACKGROUND=0

# file
export GUM_FILE_CURSOR_FOREGROUND=3
export GUM_FILE_SYMLINK_FOREGROUND=6
export GUM_FILE_DIRECTORY_FOREGROUND=4
export GUM_FILE_FILE_FOREGROUND=7
export GUM_FILE_PERMISSIONS_FOREGROUND=8
export GUM_FILE_SELECTED_FOREGROUND=3
export GUM_FILE_FILE_SIZE_FOREGROUND=15

# filter
export GUM_FILTER_INDICATOR_FOREGROUND=3
export GUM_FILTER_SELECTED_PREFIX_FOREGROUND=4
export GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND=7
export GUM_FILTER_HEADER_FOREGROUND=6
export GUM_FILTER_TEXT_FOREGROUND=8
export GUM_FILTER_CURSOR_TEXT_FOREGROUND=15
export GUM_FILTER_MATCH_FOREGROUND=7
export GUM_FILTER_PROMPT_FOREGROUND=0
export GUM_FILTER_PLACEHOLDER_FOREGROUND=0

# input
export GUM_INPUT_PROMPT_FOREGROUND=7
export GUM_INPUT_PLACEHOLDER_FOREGROUND=15
export GUM_INPUT_CURSOR_FOREGROUND=3
export GUM_INPUT_HEADER_FOREGROUND=6

# spin
export GUM_SPIN_SPINNER="points"
export GUM_SPIN_SPINNER_FOREGROUND=6
export GUM_SPIN_TITLE_FOREGROUND=7

# write
export GUM_WRITE_PROMPT=" "
export GUM_WRITE_BASE_FOREGROUND=7
export GUM_WRITE_CURSOR_FOREGROUND=3
export GUM_WRITE_HEADER_FOREGROUND=6
export GUM_WRITE_PLACEHOLDER_FOREGROUND=15
export GUM_WRITE_PROMPT_FOREGROUND=7
export GUM_WRITE_END_OF_BUFFER_FOREGROUND=1
export GUM_WRITE_LINE_NUMBER_FOREGROUND=0
export GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND=8
# export GUM_WRITE_CURSOR_LINE_FOREGROUND=""
