#!/bin/bash

if [ -z "$SSH_AUTH_SOCK" ]; then
    # Check for a currently running instance of the agent
    RUNNING_AGENT=`ps -ax | grep 'ssh-agent -s' | grep -v grep | wc -l | tr -d '[:space:]'`
    SSH_AGENT_SCRIPT="$HOME/.ssh/ssh-agent"
    if [ "$RUNNING_AGENT" = "0" ]; then
        # Launch a new instance of the agent and add existing keys
        ssh-agent -s > $SSH_AGENT_SCRIPT
        eval $(cat $SSH_AGENT_SCRIPT)
        for key in $(ls ~/.ssh/*.pub)
        do
            # Removes .pub extension
            ssh-add ${key%.pub}
        done
    else
        eval $(cat $SSH_AGENT_SCRIPT)
    fi
fi
