on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: known_hosts-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    strategy:
      matrix:
        idx:
          - host: github.com
            docs: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/githubs-ssh-key-fingerprints
          - host: gitlab.com
            docs: https://docs.gitlab.com/ee/user/gitlab_com/#ssh-known_hosts-entries
          - host: bitbucket.org
            docs: https://bitbucket.org/site/ssh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: gh-ref
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main
          ref: main

      - name: Verify ${{ matrix.idx.host }} host key
        run: |
          bash main/.github/scripts/verify-known_hosts.sh \
            gh-ref/ssh/.ssh/known_hosts \
            "${{ matrix.idx.host }}" \
            "${{ matrix.idx.docs }}"
